/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bigsleep_tsynth_micro_Glue */

#ifndef _Included_org_bigsleep_tsynth_micro_Glue
#define _Included_org_bigsleep_tsynth_micro_Glue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bigsleep_tsynth_micro_Glue
 * Method:    midiReceive
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_bigsleep_tsynth_1micro_Glue_midiReceive
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_bigsleep_tsynth_micro_Glue
 * Method:    setParameterDouble
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_bigsleep_tsynth_1micro_Glue_setParameterDouble
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     org_bigsleep_tsynth_micro_Glue
 * Method:    setParameterInt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_bigsleep_tsynth_1micro_Glue_setParameterInt
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_bigsleep_tsynth_micro_Glue
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bigsleep_tsynth_1micro_Glue_start
  (JNIEnv *, jobject);

/*
 * Class:     org_bigsleep_tsynth_micro_Glue
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bigsleep_tsynth_1micro_Glue_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
