#! /usr/bin/env python
# encoding: utf-8

VERSION='0.0.1'
APPNAME='tsynth'

top = '.'
out = 'build'

def options(opt):
    opt.load('g++')

def configure(conf):
    conf.load('g++')

def build(bld):
    bld.program(
        source = [
            'main.cpp',
            'tsynth.cpp',
            'tree.cpp',
            'midi_utility.cpp',
            'mono_synth.cpp',
            'mod_factory.cpp',
            'vco.cpp',
            'vca.cpp',
            'mixer.cpp',
            'vcf.cpp',
            'eg.cpp',
            'inv_exp_table.cpp'],
        target = 'tsynth',
        cxxflags = ['-O3', '-Wall', '-std=c++0x'])

